name: Cypress Actions CI

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn --immutable
          record: true
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
          # parallel: true
        env:
          email: ${{ secrets.email }}
          password: ${{ secrets.password }}
          baseUrl: ${{ secrets.baseUrl }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          # NEXT_BASE_HTTP: ${{ secrets.NEXT_BASE_HTTP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          NEXT_PUBLIC_HTTP: ${{ secrets.NEXT_PUBLIC_HTTP }}
